CE103 Algorithms and Programming I HW3: C:/Users/Emirhan/Desktop/odev3/finale/deneme2/DepartmentStoreManagementSystem/DepartmentStoreManagementSystem/translate.c File Reference
translate.c File Reference
#include <stdarg.h>
#include <string.h>
#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include "translate.h"
Macros
#define _CRT_SECURE_NO_WARNINGS
Functions
int getId (char *line)
char * getIdString (char *line)
void setTranslateLang (char *str, bool save)
void fixFile (FILE *fptr, bool close)
void getTranslateLang (char *lang)
void printTranslateLang (int id)
Variables
int app_language = APP_LANG_EN
Macro Definition Documentation
_CRT_SECURE_NO_WARNINGS
#define _CRT_SECURE_NO_WARNINGS
Function Documentation
fixFile()
void fixFile (FILE * fptr, bool close)
References ENGLISH_L, and LANG_CONF_FILE.
Referenced by getTranslateLang().
getId()
int getId (char * line)
Referenced by printTranslateLang().
getIdString()
char * getIdString (char * line)
Referenced by printTranslateLang().
getTranslateLang()
void getTranslateLang (char * lang)
References ENGLISH_L, fixFile(), and LANG_CONF_FILE.
Referenced by langSelection().
printTranslateLang()
void printTranslateLang (int id)
References APP_LANG_EN, APP_LANG_TR, app_language, EN_LANG_FILE, exit(), getId(), getIdString(), and TR_LANG_FILE.
Referenced by add(), bill(), c_code(), d_all(), d_code(), d_mainmenu(), d_quan(), d_rate(), d_search(), dbill(), del(), dis_con(), edit(), highlight(), langSelection(), and window().
setTranslateLang()
void setTranslateLang (char * str, bool save)
References APP_LANG_EN, APP_LANG_TR, app_language, ENGLISH_L, LANG_CONF_FILE, and TURKISH_L.
Referenced by langSelection().
Variable Documentation
app_language
int app_language = APP_LANG_EN
Referenced by printTranslateLang(), and setTranslateLang().