#pragma once

//messages are numbered with unique ID and this message translated text are  stored on en.dat and tr.dat files
#define main_menu 1
#define search_menu 2
#define by_code 3
#define by_rate 4
#define by_quantity 5
#define back_to_main_menu 6
#define calculate_bill 7
#define add_goods 8
#define edit_goods 9
#define display_all 10
#define search 11
#define delete_goods 12
#define change_language 13
#define cexit 14
#define enter_end_to_finish_input 15
#define enter_item_code 16
#define enter_quantity 17
#define total_amount_nrs 18
#define fashion_wear 19
#define departmental_store 20
#define customers_bill 21
#define sn_itemname_quantity_rate_total 22
#define enter_new_record_yn 23
#define enter_rate_of_the_item 24
#define enter_quantity_of_the_item 25
#define enter_name_of_the_item 26
#define add_articles 27
#define enter_new_code_of_the_article 28
#define code_already_exists 29
#define enter_again 30
#define edit_records 31
#define name_s 32
#define code_s 33
#define rate_g 34
#define quantity_d 35
#define do_you_want_to_edit_this_code_yn 36
#define o_edit_name 37
#define t_edit_code 38
#define t_edit_rate 39
#define f_edit_quantity 40
#define enter_your_choice_1234 41
#define enter_new_name 42
#define enter_new_rate 43
#define enter_new_quantity 44
#define item_edited 45
#define item_does_not_exist 46
#define try_again 47
#define press_any_key_to_see_more 48
#define no_articles_found 49
#define enter_lower_range 50
#define enter_upper_range 51
#define no_items_found 52
#define no_item_found 53
#define records 54
#define sn_itemname_itemcode_rate_quantity 55
#define delete_articles 56
#define item_deleted 57
#define by_code2 58
#define by_rate2 59
#define by_quantity2 60
#define back_to_main_menu2 61
#define calculate_bill2 62
#define add_goods2 63
#define edit_goods2 64
#define display_all2 65
#define search2 66
#define delete_goods2 67
#define change_language2 68
#define cexit2 69
#define change_language3 70
#define confirm_lang_change 71
#define for_english_press 72
#define for_turkish_press 73
